#List the wes runs in the cohort and the path to their summary json file
runs:
  run_01:
    - /path/to/wes/summary/json_file01.json
  run_02:
    - /path/to/wes/summary/json_file02.json
  run_03:
    - /path/to/wes/summary/json_file02.json
  #...

#BACKPORT configs:
#01_mutation_signatur-
#_bwa_index = './ref_files/hg38/bwa_gdc/GRCh38.d1.vd1.CIDC.fa'
#

#02_somaticSummaries
#The center from which the samples were processed (this will be associated
#with the center's targeted bed file
center: 'broad'

#04_addNeoantigen.py
#Associate the filter.tsv file for each sample like this
#neoantigen:
#  CNTZ27E78.01:
#  - /mnt/ssd/10021_trial_report/neoantigen/10021_wes_CNTZ27E78.01_analysis_combined_filtered.tsv
#  CNTZ4ZJYN.01:
#  - /mnt/ssd/10021_trial_report/neoantigen/10021_wes_CNTZ4ZJYN.01_analysis_combined_filtered.tsv
#  CNTZ5KQEL.01:
#  - /mnt/ssd/10021_trial_report/neoantigen/10021_wes_CNTZ5KQEL.01_analysis_combined_filtered.tsv
# ...etc...
