destination: gs://repro_10104_len/WES/fastq/concat_all/analysis/concat
path: gs://cidc-data-prod-acl/10104/wes
samples:
  CWWG1G8HZ.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWG1G8HZ.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWG1G8HZ.01/r1_L2.fastq.gz
  CWWG1G8HZ.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWG1G8HZ.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWG1G8HZ.01/r2_L2.fastq.gz
  CWWG1G8QP.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWG1G8QP.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWG1G8QP.01/r1_L2.fastq.gz
  CWWG1G8QP.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWG1G8QP.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWG1G8QP.01/r2_L2.fastq.gz
  CWWG5M5CT.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWG5M5CT.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWG5M5CT.01/r1_L2.fastq.gz
  CWWG5M5CT.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWG5M5CT.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWG5M5CT.01/r2_L2.fastq.gz
  CWWG5M5EB.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWG5M5EB.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWG5M5EB.01/r1_L2.fastq.gz
  CWWG5M5EB.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWG5M5EB.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWG5M5EB.01/r2_L2.fastq.gz
  CWWGFWP4T.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGFWP4T.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGFWP4T.01/r1_L2.fastq.gz
  CWWGFWP4T.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGFWP4T.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGFWP4T.01/r2_L2.fastq.gz
  CWWGFWPWK.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGFWPWK.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGFWPWK.01/r1_L2.fastq.gz
  CWWGFWPWK.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGFWPWK.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGFWPWK.01/r2_L2.fastq.gz
  CWWGHHE48.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGHHE48.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGHHE48.01/r1_L2.fastq.gz
  CWWGHHE48.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGHHE48.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGHHE48.01/r2_L2.fastq.gz
  CWWGHHEFS.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGHHEFS.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGHHEFS.01/r1_L2.fastq.gz
  CWWGHHEFS.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGHHEFS.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGHHEFS.01/r2_L2.fastq.gz
  CWWGIMN31.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGIMN31.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGIMN31.01/r1_L2.fastq.gz
  CWWGIMN31.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGIMN31.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGIMN31.01/r2_L2.fastq.gz
  CWWGIMN5F.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGIMN5F.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGIMN5F.01/r1_L2.fastq.gz
  CWWGIMN5F.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGIMN5F.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGIMN5F.01/r2_L2.fastq.gz
  CWWGK4ZRT.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGK4ZRT.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGK4ZRT.01/r1_L2.fastq.gz
  CWWGK4ZRT.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGK4ZRT.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGK4ZRT.01/r2_L2.fastq.gz
  CWWGK4ZTX.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGK4ZTX.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGK4ZTX.01/r1_L2.fastq.gz
  CWWGK4ZTX.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGK4ZTX.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGK4ZTX.01/r2_L2.fastq.gz
  CWWGNH3FL.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGNH3FL.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGNH3FL.01/r1_L2.fastq.gz
  CWWGNH3FL.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGNH3FL.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGNH3FL.01/r2_L2.fastq.gz
  CWWGNH3FP.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGNH3FP.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGNH3FP.01/r1_L2.fastq.gz
  CWWGNH3FP.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGNH3FP.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGNH3FP.01/r2_L2.fastq.gz
  CWWGPSHL8.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGPSHL8.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGPSHL8.01/r1_L2.fastq.gz
  CWWGPSHL8.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGPSHL8.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGPSHL8.01/r2_L2.fastq.gz
  CWWGPSHZD.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGPSHZD.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGPSHZD.01/r1_L2.fastq.gz
  CWWGPSHZD.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGPSHZD.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGPSHZD.01/r2_L2.fastq.gz
  CWWGSDRNZ.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGSDRNZ.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGSDRNZ.01/r1_L2.fastq.gz
  CWWGSDRNZ.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGSDRNZ.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGSDRNZ.01/r2_L2.fastq.gz
  CWWGSDRW7.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGSDRW7.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGSDRW7.01/r1_L2.fastq.gz
  CWWGSDRW7.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGSDRW7.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGSDRW7.01/r2_L2.fastq.gz
  CWWGSPZ02.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGSPZ02.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGSPZ02.01/r1_L2.fastq.gz
  CWWGSPZ02.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGSPZ02.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGSPZ02.01/r2_L2.fastq.gz
  CWWGSPZW5.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGSPZW5.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGSPZW5.01/r1_L2.fastq.gz
  CWWGSPZW5.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGSPZW5.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGSPZW5.01/r2_L2.fastq.gz
  CWWGTQ44D.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGTQ44D.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGTQ44D.01/r1_L2.fastq.gz
  CWWGTQ44D.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGTQ44D.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGTQ44D.01/r2_L2.fastq.gz
  CWWGTQ4MI.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGTQ4MI.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGTQ4MI.01/r1_L2.fastq.gz
  CWWGTQ4MI.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGTQ4MI.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGTQ4MI.01/r2_L2.fastq.gz
  CWWGUKK3W.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGUKK3W.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGUKK3W.01/r1_L2.fastq.gz
  CWWGUKK3W.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGUKK3W.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGUKK3W.01/r2_L2.fastq.gz
  CWWGUKKTP.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGUKKTP.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGUKKTP.01/r1_L2.fastq.gz
  CWWGUKKTP.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGUKKTP.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGUKKTP.01/r2_L2.fastq.gz
  CWWGUVJLE.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGUVJLE.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGUVJLE.01/r1_L2.fastq.gz
  CWWGUVJLE.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGUVJLE.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGUVJLE.01/r2_L2.fastq.gz
  CWWGUVJOB.01_R1:
  - gs://cidc-data-prod-acl/10104/wes/CWWGUVJOB.01/r1_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGUVJOB.01/r1_L2.fastq.gz
  CWWGUVJOB.01_R2:
  - gs://cidc-data-prod-acl/10104/wes/CWWGUVJOB.01/r2_L1.fastq.gz
  - gs://cidc-data-prod-acl/10104/wes/CWWGUVJOB.01/r2_L2.fastq.gz
