broad-Run1-pt2-FF: {tumor: R1-2-F, normal: R1-2-N}
broad-Run1-pt3-FF: {tumor: R1-3-F, normal: R1-3-N}
broad-Run1-pt4-FF: {tumor: R1-4-F, normal: R1-4-N}
broad-Run1-pt5-FF: {tumor: R1-5-F, normal: R1-5-N}
broad-Run1-pt6-FF: {tumor: R1-6-F, normal: R1-6-N}
broad-Run1-pt7-FF: {tumor: R1-7-F, normal: R1-7-N}
broad-Run1-pt8-FF: {tumor: R1-8-F, normal: R1-8-N}

mocha2-Run1-pt1-FF: {tumor: mocha-Run1-pt1-FF-Tumor, normal: mocha-Run1-pt1-Normal}
mocha2-Run1-pt2-FF: {tumor: mocha-Run1-pt2-FF-Tumor, normal: mocha-Run1-pt2-Normal}
mocha2-Run1-pt3-FF: {tumor: mocha-Run1-pt3-FF-Tumor, normal: mocha-Run1-pt3-Normal}
mocha2-Run1-pt4-FF: {tumor: mocha-Run1-pt4-FF-Tumor, normal: mocha-Run1-pt4-Normal}
mocha2-Run1-pt5-FF: {tumor: mocha-Run1-pt5-FF-Tumor, normal: mocha-Run1-pt5-Normal}
mocha2-Run1-pt6-FF: {tumor: mocha-Run1-pt6-FF-Tumor, normal: mocha-Run1-pt6-Normal}
mocha2-Run1-pt8-FF: {tumor: mocha-Run1-pt8-FF-Tumor, normal: mocha-Run1-pt8-Normal}

MDA-Run1-pt1-FF: {tumor: MDA-Run1-pt1-FF-Tumor, normal: MDA-Run1-pt1-Normal}
MDA-Run1-pt2-FF: {tumor: MDA-Run1-pt2-FF-Tumor, normal: MDA-Run1-pt2-Normal}
MDA-Run1-pt3-FF: {tumor: MDA-Run1-pt3-FF-Tumor, normal: MDA-Run1-pt3-Normal}
MDA-Run1-pt5-FF: {tumor: MDA-Run1-pt5-FF-Tumor, normal: MDA-Run1-pt5-Normal}
MDA-Run1-pt6-FF: {tumor: MDA-Run1-pt6-FF-Tumor, normal: MDA-Run1-pt6-Normal}
MDA-Run1-pt7-FF: {tumor: MDA-Run1-pt7-FF-Tumor, normal: MDA-Run1-pt7-Normal}
MDA-Run1-pt8-FF: {tumor: MDA-Run1-pt8-FF-Tumor, normal: MDA-Run1-pt8-Normal}

