sentieon_path: '/home/taing/sentieon/sentieon-genomics-202010.01/bin'
bwa_index: ./ref_files/hg38/bwa_gdc/GRCh38.d1.vd1.CIDC.fa
genome_fasta: ./ref_files/hg38/bwa_gdc/GRCh38.d1.vd1.CIDC.fa
dbsnp: ./ref_files/hg38/snp/Homo_sapiens_assembly38.dbsnp138.vcf
Mills_indels: ./ref_files/hg38/snp/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
G1000_indels: ./ref_files/hg38/snp/1000G_phase1.snps.high_confidence.hg38.vcf.gz

center: 'cidc' #define this for the set of normals given
pon_files:
#  - input_pons/broad.pon.vcf.gz
#  - input_pons/mocha.pon.vcf.gz
#  - input_pons/MDA.pon.vcf.gz
  - input_pons/10021_pon.noInfo.vcf.gz
  - input_pons/s1400i.pon.noInfo.vcf.gz
  - input_pons/10026.pon.noInfo.vcf.gz
  - input_pons/S1609.pon.noInfo.vcf.gz
  - input_pons/10104.pon.noInfo.vcf.gz
